# Generated by Django 5.2.10 on 2026-01-27 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('timetracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=100, verbose_name='Template Naam')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout Configuratie')),
                ('variables', models.JSONField(default=dict, verbose_name='Variabelen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factuur Template',
                'verbose_name_plural': 'Factuur Templates',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factuurnummer', models.CharField(max_length=50, unique=True, verbose_name='Factuurnummer')),
                ('type', models.CharField(choices=[('inkoop', 'Inkoop'), ('verkoop', 'Verkoop'), ('credit', 'Credit')], default='verkoop', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('definitief', 'Definitief'), ('verzonden', 'Verzonden'), ('betaald', 'Betaald')], default='concept', max_length=20, verbose_name='Status')),
                ('factuurdatum', models.DateField(verbose_name='Factuurdatum')),
                ('vervaldatum', models.DateField(verbose_name='Vervaldatum')),
                ('subtotaal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotaal')),
                ('btw_percentage', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='BTW %')),
                ('btw_bedrag', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BTW Bedrag')),
                ('totaal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totaal')),
                ('opmerkingen', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Verzonden op')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='companies.company', verbose_name='Bedrijf')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.invoicetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Factuur',
                'verbose_name_plural': 'Facturen',
                'ordering': ['-factuurdatum', '-factuurnummer'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=500, verbose_name='Omschrijving')),
                ('aantal', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Aantal')),
                ('eenheid', models.CharField(default='stuk', max_length=20, verbose_name='Eenheid')),
                ('prijs_per_eenheid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prijs/Eenheid')),
                ('totaal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totaal')),
                ('extra_data', models.JSONField(default=dict, verbose_name='Extra Data')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Factuur')),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='timetracking.timeentry', verbose_name='Urenregistratie')),
            ],
            options={
                'verbose_name': 'Factuur Regel',
                'verbose_name_plural': 'Factuur Regels',
                'ordering': ['volgorde'],
            },
        ),
    ]
