# Generated by Django 5.2.10 on 2026-01-29 05:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=255, verbose_name='Omschrijving')),
                ('categorie', models.CharField(choices=[('brandstof', 'Brandstof'), ('onderhoud', 'Onderhoud & Reparatie'), ('verzekering', 'Verzekering'), ('belasting', 'Wegenbelasting'), ('lease', 'Lease / Huur'), ('personeelskosten', 'Personeelskosten'), ('kantoorkosten', 'Kantoorkosten'), ('marketing', 'Marketing & Reclame'), ('software', 'Software & Abonnementen'), ('overig', 'Overig')], default='overig', max_length=30, verbose_name='Categorie')),
                ('bedrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bedrag (excl. BTW)')),
                ('btw_bedrag', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BTW Bedrag')),
                ('totaal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totaal (incl. BTW)')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('notities', models.TextField(blank=True, verbose_name='Notities')),
                ('bijlage', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='Bijlage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrijf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='companies.company', verbose_name='Leverancier')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='drivers.driver', verbose_name='Chauffeur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('voertuig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fleet.vehicle', verbose_name='Voertuig')),
            ],
            options={
                'verbose_name': 'Uitgave',
                'verbose_name_plural': 'Uitgaven',
                'ordering': ['-datum', '-created_at'],
            },
        ),
    ]
