# Generated by Django 5.2.10 on 2026-01-30 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_add_expense_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weeknummer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='week_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jaar (voor week)'),
        ),
    ]
