# Generated by Django 5.2.11 on 2026-02-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_add_week_chauffeur_to_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoicing.invoicetemplate', verbose_name='Template'),
        ),
    ]
