# Generated by Django 5.2.12 on 2026-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0004_alter_invoice_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bijlage",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/bijlagen/",
                verbose_name="Bijlage",
            ),
        ),
    ]
