# Generated by Django 5.2.12 on 2026-05-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0005_add_bijlage_to_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dot_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DOT percentage gebruikt bij importeren van uren (bijv. 21 voor 21%)",
                max_digits=5,
                null=True,
                verbose_name="DOT Percentage",
            ),
        ),
    ]
