# Generated by Django 5.2.12 on 2026-03-31 10:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0006_driver_expiry_dates'),
        ('fleet', '0005_remove_old_kenteken_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Gestart op')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestopt op')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_sessions', to='fleet.vehicle', verbose_name='Voertuig')),
            ],
            options={
                'verbose_name': 'Tracking Sessie',
                'verbose_name_plural': 'Tracking Sessies',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Breedtegraad')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Lengtegraad')),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters. Lower is better.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Nauwkeurigheid (m)')),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h. Max 400 for sanity check.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='Snelheid (km/h)')),
                ('heading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Richting (graden)')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Hoogte (m)')),
                ('recorded_at', models.DateTimeField(help_text='Client-side timestamp of this location point.', verbose_name='Opgenomen op')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Server-side timestamp when point was received.', verbose_name='Ontvangen op')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracking.trackingsession', verbose_name='Sessie')),
            ],
            options={
                'verbose_name': 'Locatiepunt',
                'verbose_name_plural': 'Locatiepunten',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TachographOvertime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Datum')),
                ('overtime_hours', models.DecimalField(decimal_places=2, help_text='Aantal overuren (boven 8 uur).', max_digits=5, verbose_name='Overuren')),
                ('vehicle_name', models.CharField(blank=True, max_length=100, verbose_name='Voertuig')),
                ('fm_driver_name', models.CharField(blank=True, max_length=200, verbose_name='FM-Track Chauffeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tachograph_overtime', to='drivers.driver', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Tachograaf Overuren',
                'verbose_name_plural': 'Tachograaf Overuren',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['user', 'is_active'], name='tracking_tr_user_id_acc108_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['vehicle', 'is_active'], name='tracking_tr_vehicle_7485a3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['-started_at'], name='tracking_tr_started_fc2e63_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['session', '-recorded_at'], name='tracking_lo_session_b5c21c_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['-received_at'], name='tracking_lo_receive_b4406c_idx'),
        ),
    ]
