# Generated by Django 5.2.10 on 2026-02-27 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.TextField(help_text='De volledige gesigneerde licentiesleutel (payload.signature)', unique=True)),
                ('customer_name', models.CharField(help_text='Klantnaam', max_length=255)),
                ('issued_at', models.DateTimeField(help_text='Datum van uitgifte')),
                ('expires_at', models.DateTimeField(help_text='Verloopdatum')),
                ('max_users', models.PositiveIntegerField(default=0, help_text='Maximum aantal gebruikers (0 = onbeperkt)')),
                ('features', models.JSONField(blank=True, default=list, help_text='Beschikbare modules/features')),
                ('installation_id', models.CharField(blank=True, help_text='Unieke installatie-identifier (gegenereerd bij activatie)', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('active', 'Actief'), ('expired', 'Verlopen'), ('revoked', 'Ingetrokken')], default='pending', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licentie',
                'verbose_name_plural': 'Licenties',
                'ordering': ['-created_at'],
            },
        ),
    ]
