# Generated by Django 5.2.10 on 2026-01-30 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('none', 'Uitgeschakeld'), ('webpush', 'Web Push (VAPID) - Gratis'), ('firebase', 'Firebase Cloud Messaging (FCM)')], default='none', max_length=20, verbose_name='Push Provider')),
                ('vapid_public_key', models.TextField(blank=True, null=True, verbose_name='VAPID Public Key')),
                ('vapid_private_key_encrypted', models.TextField(blank=True, null=True, verbose_name='VAPID Private Key (encrypted)')),
                ('vapid_admin_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='VAPID Admin Email')),
                ('firebase_project_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firebase Project ID')),
                ('firebase_api_key_encrypted', models.TextField(blank=True, null=True, verbose_name='Firebase API Key (encrypted)')),
                ('firebase_sender_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firebase Sender ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Push Settings',
                'verbose_name_plural': 'Push Settings',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_to_all', models.BooleanField(default=False, verbose_name='Send to All')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='Icon URL')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Click URL')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Extra Data')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('success_count', models.IntegerField(default=0, verbose_name='Success Count')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Failure Count')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(verbose_name='Push Endpoint')),
                ('p256dh_key', models.TextField(verbose_name='P256DH Key')),
                ('auth_key', models.TextField(verbose_name='Auth Key')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
