# Generated by Django 5.2.10 on 2026-01-30 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Naam')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschrijving')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='companies.company', verbose_name='Bedrijf')),
                ('members', models.ManyToManyField(blank=True, related_name='notification_groups', to=settings.AUTH_USER_MODEL, verbose_name='Leden')),
            ],
            options={
                'verbose_name': 'Notificatie Groep',
                'verbose_name_plural': 'Notificatie Groepen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationgroup', verbose_name='Groep'),
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Naam')),
                ('frequency', models.CharField(choices=[('daily', 'Dagelijks'), ('weekdays', 'Alleen werkdagen (ma-vr)'), ('weekend', 'Alleen weekend (za-zo)'), ('weekly', 'Wekelijks (specifieke dag)'), ('custom', 'Aangepaste dagen')], default='daily', max_length=20, verbose_name='Frequentie')),
                ('weekly_day', models.IntegerField(blank=True, choices=[(0, 'Maandag'), (1, 'Dinsdag'), (2, 'Woensdag'), (3, 'Donderdag'), (4, 'Vrijdag'), (5, 'Zaterdag'), (6, 'Zondag')], null=True, verbose_name='Dag van de week')),
                ('custom_days', models.JSONField(blank=True, default=list, verbose_name='Aangepaste dagen')),
                ('send_time', models.TimeField(verbose_name='Verzendtijd')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('body', models.TextField(verbose_name='Bericht')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='Icon URL')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatst verzonden')),
                ('next_send_at', models.DateTimeField(blank=True, null=True, verbose_name='Volgende verzending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='notifications.notificationgroup', verbose_name='Groep')),
            ],
            options={
                'verbose_name': 'Notificatie Schema',
                'verbose_name_plural': "Notificatie Schema's",
                'ordering': ['send_time', 'name'],
            },
        ),
    ]
