# Generated by Django 5.2.10 on 2026-01-30 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationgroup_pushnotification_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelezen')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelezen op')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notifications.pushnotification', verbose_name='Notificatie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Gebruiker Notificatie',
                'verbose_name_plural': 'Gebruiker Notificaties',
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
