# Generated by Django 5.2.10 on 2026-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_user_notification_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsettings',
            name='notification_poll_interval',
            field=models.IntegerField(default=10, help_text='Hoe vaak de notificatie-teller wordt bijgewerkt (in seconden)', verbose_name='Poll Interval (seconden)'),
        ),
    ]
