# Generated by Django 5.2.10 on 2026-01-27 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(default='TMS', max_length=100, verbose_name='Applicatie Naam')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Primaire Kleur')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Bedrijfsnaam')),
                ('company_address', models.TextField(blank=True, verbose_name='Adres')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefoon')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('company_kvk', models.CharField(blank=True, max_length=20, verbose_name='KVK Nummer')),
                ('company_btw', models.CharField(blank=True, max_length=20, verbose_name='BTW Nummer')),
                ('company_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Poort')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='SMTP Gebruikersnaam')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP Wachtwoord')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Gebruik TLS')),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254, verbose_name='Van E-mail')),
                ('oauth_enabled', models.BooleanField(default=False, verbose_name='OAuth Ingeschakeld')),
                ('oauth_client_id', models.CharField(blank=True, max_length=255, verbose_name='OAuth Client ID')),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255, verbose_name='OAuth Client Secret')),
                ('oauth_tenant_id', models.CharField(blank=True, max_length=255, verbose_name='OAuth Tenant ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Instellingen',
                'verbose_name_plural': 'App Instellingen',
            },
        ),
    ]
