# Generated by Django 5.2.10 on 2026-01-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='email_signature',
            field=models.TextField(blank=True, default='', help_text='Handtekening die onderaan alle uitgaande e-mails wordt toegevoegd.', verbose_name='E-mail Handtekening'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_payment_text',
            field=models.TextField(blank=True, default='Wij verzoeken u vriendelijk het totaalbedrag vóór de vervaldatum over te maken op bovenstaand IBAN onder vermelding van het factuurnummer.', help_text='Tekst die onderaan de factuur wordt getoond. Gebruik {bedrag}, {vervaldatum} en {factuurnummer} als variabelen.', verbose_name='Factuur Betalingstekst'),
        ),
    ]
