# Generated by Django 5.2.10 on 2026-01-29 05:06

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_invoice_payment_text_and_email_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family', models.CharField(help_text='Naam van de font familie (bijv. "Roboto", "Open Sans")', max_length=100, verbose_name='Font Familie')),
                ('name', models.CharField(help_text='Weergavenaam voor dit font', max_length=100, verbose_name='Naam')),
                ('font_file', models.FileField(upload_to=apps.core.models.font_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['woff', 'woff2', 'ttf', 'otf']), apps.core.models.validate_font_file], verbose_name='Font Bestand')),
                ('weight', models.PositiveIntegerField(choices=[(100, 'Thin (100)'), (200, 'Extra Light (200)'), (300, 'Light (300)'), (400, 'Regular (400)'), (500, 'Medium (500)'), (600, 'Semi Bold (600)'), (700, 'Bold (700)'), (800, 'Extra Bold (800)'), (900, 'Black (900)')], default=400, verbose_name='Gewicht')),
                ('style', models.CharField(choices=[('normal', 'Normaal'), ('italic', 'Cursief')], default='normal', max_length=10, verbose_name='Stijl')),
                ('is_system', models.BooleanField(default=False, help_text='Systeemfonts kunnen niet worden verwijderd', verbose_name='Systeemfont')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Geüpload door')),
            ],
            options={
                'verbose_name': 'Custom Font',
                'verbose_name_plural': 'Custom Fonts',
                'ordering': ['family', 'weight', 'style'],
                'unique_together': {('family', 'weight', 'style')},
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='primary_font',
            field=models.ForeignKey(blank=True, help_text='Het hoofdfont voor de applicatie (koppen en tekst)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_settings', to='core.customfont', verbose_name='Primair Font'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='secondary_font',
            field=models.ForeignKey(blank=True, help_text='Optioneel secundair font (voor accenten)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for_settings', to='core.customfont', verbose_name='Secundair Font'),
        ),
    ]
