# Generated by Django 5.2.10 on 2026-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_custom_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ai_azure_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Azure OpenAI API Key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_azure_deployment',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=100, verbose_name='Azure Deployment Name'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_azure_endpoint',
            field=models.CharField(blank=True, help_text='Bijv: https://your-resource.openai.azure.com/', max_length=255, verbose_name='Azure OpenAI Endpoint'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_github_token',
            field=models.CharField(blank=True, help_text='GitHub Personal Access Token met "models" permissie (gratis)', max_length=255, verbose_name='GitHub Token'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', help_text='Model naam (bijv: gpt-4o-mini, gpt-4o)', max_length=50, verbose_name='AI Model'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_openai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI API key (betaald)', max_length=255, verbose_name='OpenAI API Key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_provider',
            field=models.CharField(choices=[('github', 'GitHub Models (Gratis)'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('none', 'Uitgeschakeld')], default='none', help_text='Kies welke AI provider gebruikt wordt voor factuur extractie', max_length=20, verbose_name='AI Provider'),
        ),
    ]
