# Generated by Django 5.2.10 on 2026-01-29 13:07

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_ai_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='ai_azure_api_key',
            field=apps.core.models.EncryptedCharField(blank=True, max_length=512, verbose_name='Azure OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='ai_github_token',
            field=apps.core.models.EncryptedCharField(blank=True, help_text='GitHub Personal Access Token met "models" permissie (gratis)', max_length=512, verbose_name='GitHub Token'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='ai_openai_api_key',
            field=apps.core.models.EncryptedCharField(blank=True, help_text='OpenAI API key (betaald)', max_length=512, verbose_name='OpenAI API Key'),
        ),
    ]
