# Generated by Django 5.2.10 on 2026-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='invoice_start_number_credit',
            field=models.PositiveIntegerField(default=1, help_text='Nummer waarmee de telling begint voor creditfacturen (C-JAAR-XXXX)', verbose_name='Startnummer Creditfacturen'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_start_number_inkoop',
            field=models.PositiveIntegerField(default=1, help_text='Nummer waarmee de telling begint voor inkoopfacturen (I-JAAR-XXXX)', verbose_name='Startnummer Inkoopfacturen'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_start_number_verkoop',
            field=models.PositiveIntegerField(default=1, help_text='Nummer waarmee de telling begint voor verkoopfacturen (F-JAAR-XXXX)', verbose_name='Startnummer Verkoopfacturen'),
        ),
    ]
