# Generated by Django 5.2.10 on 2026-02-02 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_invoice_start_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Aangemaakt'), ('updated', 'Bijgewerkt'), ('deleted', 'Verwijderd'), ('submitted', 'Ingediend'), ('approved', 'Goedgekeurd'), ('rejected', 'Afgewezen'), ('sent', 'Verzonden'), ('login', 'Ingelogd'), ('logout', 'Uitgelogd')], max_length=20, verbose_name='Actie')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Entiteit type')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='Entiteit ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-adres')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tijdstip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Activiteit',
                'verbose_name_plural': 'Activiteiten',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx'), models.Index(fields=['entity_type', '-created_at'], name='core_activi_entity__e74002_idx')],
            },
        ),
    ]
