# Generated by Django 5.2.10 on 2026-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='login_background_color',
            field=models.CharField(default='#F9FAFB', max_length=7, verbose_name='Login Achtergrondkleur'),
        ),
    ]
