# Generated by Django 5.2.12 on 2026-03-30 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_login_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='reminder_custom_days',
            field=models.JSONField(blank=True, default=list, help_text='Op welke dagen herinneringen worden verstuurd (bij aangepaste frequentie).', verbose_name='Aangepaste dagen'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_email',
            field=models.EmailField(blank=True, help_text='E-mailadres waarnaar herinneringen worden verstuurd. Laat leeg voor bedrijfs-e-mail.', max_length=254, verbose_name='Ontvanger E-mail'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Schakel automatische herinneringen in voor verlopen chauffeursdocumenten.', verbose_name='Herinneringen Ingeschakeld'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_frequency',
            field=models.CharField(choices=[('daily', 'Dagelijks'), ('weekdays', 'Werkdagen (ma-vr)'), ('weekly', 'Wekelijks'), ('custom', 'Aangepast')], default='daily', help_text='Hoe vaak herinneringen worden verstuurd.', max_length=20, verbose_name='Frequentie'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_signature',
            field=models.TextField(blank=True, default='', help_text='Handtekening die onderaan herinneringsmails wordt toegevoegd.', verbose_name='Herinnering Handtekening'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Tijdstip waarop herinneringen worden verstuurd.', verbose_name='Verzendtijdstip'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_weekly_day',
            field=models.IntegerField(choices=[(0, 'Maandag'), (1, 'Dinsdag'), (2, 'Woensdag'), (3, 'Donderdag'), (4, 'Vrijdag'), (5, 'Zaterdag'), (6, 'Zondag')], default=0, help_text='Op welke dag herinneringen worden verstuurd (bij wekelijkse frequentie).', verbose_name='Dag van de week'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='reminder_weeks_before',
            field=models.JSONField(blank=True, default=list, help_text='Hoeveel weken voor de verloopdatum herinneringen worden verstuurd.', verbose_name='Weken van tevoren'),
        ),
    ]
