# Generated by Django 5.2.12 on 2026-03-31 10:45

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_reminder_job_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='linqo_api_key',
            field=apps.core.models.EncryptedCharField(blank=True, help_text='API key voor FM-Track / Linqo tachograaf koppeling.', max_length=512, verbose_name='Linqo API Key'),
        ),
    ]
