# Generated by Django 5.2.10 on 2026-02-20 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_add_mailing_list_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam', models.CharField(help_text='Naam van de spreadsheet', max_length=255, verbose_name='Naam')),
                ('week_nummer', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('jaar', models.PositiveIntegerField(verbose_name='Jaar')),
                ('tarief_per_uur', models.DecimalField(decimal_places=2, default=38.0, max_digits=10, verbose_name='Tarief per uur')),
                ('tarief_per_km', models.DecimalField(decimal_places=2, default=0.38, max_digits=10, verbose_name='Tarief per km')),
                ('tarief_dot', models.DecimalField(decimal_places=2, default=0.22, max_digits=10, verbose_name='Tarief DOT')),
                ('rijen', models.JSONField(blank=True, default=list, help_text='Array van ritregistratie rijen', verbose_name='Rijen')),
                ('notities', models.TextField(blank=True, default='', verbose_name='Notities')),
                ('totaal_factuur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Totaal factuur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Bijgewerkt op')),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spreadsheets', to='companies.company', verbose_name='Bedrijf')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spreadsheets', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
            ],
            options={
                'verbose_name': 'Spreadsheet',
                'verbose_name_plural': 'Spreadsheets',
                'ordering': ['-jaar', '-week_nummer', '-updated_at'],
            },
        ),
    ]
