# Generated by Django 5.2.10 on 2026-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='status',
            field=models.CharField(choices=[('concept', 'Concept'), ('ingediend', 'Ingediend')], default='concept', max_length=20, verbose_name='Status'),
        ),
    ]
