# Generated by Django 5.2.10 on 2026-02-20 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheets', '0002_spreadsheet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=150, verbose_name='Template naam')),
                ('beschrijving', models.TextField(blank=True, default='', verbose_name='Beschrijving')),
                ('kolommen', models.JSONField(default=list, help_text='Kolom-definities: id, naam, type, breedte, formule, styling', verbose_name='Kolommen')),
                ('footer', models.JSONField(blank=True, default=dict, verbose_name='Footer configuratie')),
                ('standaard_tarieven', models.JSONField(blank=True, default=dict, verbose_name='Standaard tarieven')),
                ('styling', models.JSONField(blank=True, default=dict, verbose_name='Styling configuratie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spreadsheet Template',
                'verbose_name_plural': 'Spreadsheet Templates',
                'ordering': ['naam'],
            },
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spreadsheets', to='spreadsheets.spreadsheettemplate', verbose_name='Template'),
        ),
    ]
