# Generated by Django 5.2.13 on 2026-05-04 07:57

import apps.dossiers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dossiertype',
                'verbose_name_plural': 'Dossiertypen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onderwerp', models.CharField(max_length=255, verbose_name='Onderwerp')),
                ('inhoud', models.TextField(verbose_name='Inhoud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betreft_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_als_chauffeur', to=settings.AUTH_USER_MODEL, verbose_name='Betreft chauffeur')),
                ('betreft_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_als_gebruiker', to=settings.AUTH_USER_MODEL, verbose_name='Betreft gebruiker')),
                ('instuurder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingediende_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Instuurder')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='dossiers.dossiertype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierReactie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tekst', models.TextField(verbose_name='Tekst')),
                ('intern', models.BooleanField(default=False, verbose_name='Intern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_reacties', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacties', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Dossierreactie',
                'verbose_name_plural': 'Dossierreacties',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierBijlage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bestand', models.FileField(upload_to=apps.dossiers.models.dossier_bijlage_upload_path, verbose_name='Bestand')),
                ('bestandsnaam', models.CharField(max_length=255, verbose_name='Bestandsnaam')),
                ('mimetype', models.CharField(blank=True, max_length=100, verbose_name='Mimetype')),
                ('grootte', models.PositiveIntegerField(default=0, verbose_name='Grootte (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bijlagen', to='dossiers.dossier', verbose_name='Dossier')),
                ('geupload_door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_bijlagen', to=settings.AUTH_USER_MODEL, verbose_name='Geüpload door')),
                ('reactie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bijlagen', to='dossiers.dossierreactie', verbose_name='Reactie')),
            ],
            options={
                'verbose_name': 'Dossierbijlage',
                'verbose_name_plural': 'Dossierbijlagen',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
