# Generated by Django 5.2.13 on 2026-05-04 07:57

from django.db import migrations
import uuid


def seed_dossier_types(apps, schema_editor):
    DossierType = apps.get_model('dossiers', 'DossierType')
    initial_types = ['Verzekeringen', 'Contracten']
    for naam in initial_types:
        DossierType.objects.get_or_create(naam=naam, defaults={'id': uuid.uuid4(), 'actief': True})


def reverse_seed(apps, schema_editor):
    DossierType = apps.get_model('dossiers', 'DossierType')
    DossierType.objects.filter(naam__in=['Verzekeringen', 'Contracten']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_dossier_types, reverse_seed),
    ]

