# Generated by Django 5.2.13 on 2026-05-04 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossiers", "0002_seed_initial_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisatie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naam",
                    models.CharField(max_length=255, unique=True, verbose_name="Naam"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefoon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefoon"
                    ),
                ),
                (
                    "opmerkingen",
                    models.TextField(blank=True, verbose_name="Opmerkingen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organisatie",
                "verbose_name_plural": "Organisaties",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="DossierMailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ontvangers", models.TextField(verbose_name="Ontvangers")),
                (
                    "onderwerp",
                    models.CharField(max_length=255, verbose_name="Onderwerp"),
                ),
                ("verzonden_op", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maillogs",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
                (
                    "verzonden_door",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossier_mails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verzonden door",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossiermail",
                "verbose_name_plural": "Dossiermails",
                "ordering": ["-verzonden_op"],
            },
        ),
        migrations.CreateModel(
            name="Contactpersoon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naam", models.CharField(max_length=255, verbose_name="Naam")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefoon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefoon"
                    ),
                ),
                (
                    "functie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Functie / rol"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactpersonen",
                        to="dossiers.organisatie",
                        verbose_name="Organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contactpersoon",
                "verbose_name_plural": "Contactpersonen",
                "ordering": ["naam"],
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="organisatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dossiers",
                to="dossiers.organisatie",
                verbose_name="Organisatie / leverancier",
            ),
        ),
    ]
