# Generated by Django 5.2.10 on 2026-01-27 21:31

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weeknummer', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('ritnummer', models.CharField(max_length=50, verbose_name='Ritnummer')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('kenteken', models.CharField(max_length=20, verbose_name='Kenteken')),
                ('km_start', models.PositiveIntegerField(verbose_name='KM Start')),
                ('km_eind', models.PositiveIntegerField(verbose_name='KM Eind')),
                ('totaal_km', models.PositiveIntegerField(editable=False, verbose_name='Totaal KM')),
                ('aanvang', models.TimeField(verbose_name='Aanvang')),
                ('eind', models.TimeField(verbose_name='Eind')),
                ('pauze', models.DurationField(default=datetime.timedelta(0), verbose_name='Pauze')),
                ('totaal_uren', models.DurationField(editable=False, verbose_name='Totaal Uren')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('ingediend', 'Ingediend')], default='concept', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Urenregistratie',
                'verbose_name_plural': 'Urenregistraties',
                'ordering': ['-datum', '-aanvang'],
            },
        ),
    ]
