# Generated by Django 5.2.10 on 2026-01-27 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kenteken', models.CharField(max_length=20, unique=True, verbose_name='Kenteken')),
                ('type_wagen', models.CharField(max_length=100, verbose_name='Type Wagen')),
                ('ritnummer', models.CharField(max_length=50, verbose_name='Ritnummer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company', verbose_name='Bedrijf')),
            ],
            options={
                'verbose_name': 'Voertuig',
                'verbose_name_plural': 'Voertuigen',
                'ordering': ['kenteken'],
            },
        ),
    ]
