# Generated by Django 5.2.11 on 2026-03-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='minimum_uren_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standaard minimum uren per week voor deze chauffeur. Wordt gebruikt als er geen specifieke weekinstelling is.', max_digits=5, null=True, verbose_name='Minimum uren per week'),
        ),
    ]
