# Generated by Django 5.2.12 on 2026-03-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_mailing_list_contact'),
        ('drivers', '0007_driver_standaard_pauze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='actief',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bedrijven',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='einddatum_adr',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='einddatum_bestuurderspas',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='einddatum_code95',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='einddatum_rijbewijs',
        ),
        migrations.AddField(
            model_name='driver',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='companies.company', verbose_name='Bedrijf'),
        ),
    ]
