# Generated by Django 5.2.12 on 2026-03-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_remove_bedrijven_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='auto_uren',
            field=models.BooleanField(default=False, help_text='Automatisch tijdregistratie aanmaken op basis van tachograaf gegevens.', verbose_name='Automatisch uren registreren'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tacho_kenteken',
            field=models.CharField(blank=True, default='', help_text='Kenteken uit de tachograaf lijst om deze chauffeur aan te koppelen.', max_length=20, verbose_name='Tachograaf kenteken'),
        ),
    ]
