# Generated by Django 5.2.12 on 2026-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_auto_uren_tacho_kenteken'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='standaard_begintijd',
            field=models.TimeField(blank=True, help_text='Vaste begintijd voor automatische uren. Als ingesteld wordt deze altijd gebruikt als aanvangstijd in plaats van de tachograaf starttijd.', null=True, verbose_name='Standaard begintijd'),
        ),
    ]
