# Generated by Django 5.2.10 on 2026-01-27 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Gebruikersnaam')),
                ('voornaam', models.CharField(max_length=100, verbose_name='Voornaam')),
                ('achternaam', models.CharField(max_length=100, verbose_name='Achternaam')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoon')),
                ('bedrijf', models.CharField(blank=True, max_length=200, verbose_name='Bedrijf')),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('gebruiker', 'Gebruiker'), ('chauffeur', 'Chauffeur')], default='gebruiker', max_length=20, verbose_name='Rol')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='2FA Ingeschakeld')),
                ('mfa_secret', models.CharField(blank=True, max_length=32, verbose_name='2FA Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Laatste login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Gebruiker',
                'verbose_name_plural': 'Gebruikers',
                'ordering': ['achternaam', 'voornaam'],
            },
        ),
    ]
