# Generated by Django 5.2.10 on 2026-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False, verbose_name='2FA Verplicht'),
        ),
    ]
