# Generated by Django 5.2.12 on 2026-03-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Lijst van specifieke rechten voor deze gebruiker, bovenop de basisrol.', verbose_name='Module rechten'),
        ),
    ]
