# Generated by Django 5.2.10 on 2026-01-27 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=200, verbose_name='Naam')),
                ('kvk', models.CharField(blank=True, max_length=20, verbose_name='KVK Nummer')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoon')),
                ('contactpersoon', models.CharField(blank=True, max_length=200, verbose_name='Contactpersoon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adres', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('stad', models.CharField(blank=True, max_length=100, verbose_name='Stad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bedrijf',
                'verbose_name_plural': 'Bedrijven',
                'ordering': ['naam'],
            },
        ),
    ]
