# Generated by Django 5.2.10 on 2026-02-20 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=200, verbose_name='Naam')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('functie', models.CharField(blank=True, max_length=200, verbose_name='Functie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_contacts', to='companies.company', verbose_name='Bedrijf')),
            ],
            options={
                'verbose_name': 'Mailinglijst contact',
                'verbose_name_plural': 'Mailinglijst contacten',
                'ordering': ['naam'],
                'unique_together': {('bedrijf', 'email')},
            },
        ),
    ]
