# Generated by Django 5.2.10 on 2026-01-29 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('invoicing', '0002_add_expense_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='imports/invoices/', verbose_name='Origineel Bestand')),
                ('file_name', models.CharField(max_length=255, verbose_name='Bestandsnaam')),
                ('file_type', models.CharField(max_length=20, verbose_name='Bestandstype')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Bestandsgrootte')),
                ('status', models.CharField(choices=[('pending', 'In wachtrij'), ('processing', 'Verwerken'), ('extracted', 'Geëxtraheerd'), ('review', 'Review nodig'), ('completed', 'Voltooid'), ('failed', 'Mislukt')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Foutmelding')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR Tekst')),
                ('ocr_confidence', models.FloatField(blank=True, null=True, verbose_name='OCR Confidence')),
                ('extracted_data', models.JSONField(default=dict, verbose_name='Geëxtraheerde Data')),
                ('user_corrections', models.JSONField(default=dict, verbose_name='Gebruiker Correcties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_source', to='invoicing.invoice', verbose_name='Aangemaakte Factuur')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_imports', to=settings.AUTH_USER_MODEL, verbose_name='Geüpload door')),
            ],
            options={
                'verbose_name': 'Factuur Import',
                'verbose_name_plural': 'Factuur Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(blank=True, max_length=500, verbose_name='Omschrijving')),
                ('aantal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aantal')),
                ('eenheid', models.CharField(blank=True, max_length=20, verbose_name='Eenheid')),
                ('prijs_per_eenheid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prijs/Eenheid')),
                ('totaal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Totaal')),
                ('btw_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BTW %')),
                ('raw_text', models.TextField(blank=True, verbose_name='Ruwe Tekst')),
                ('position', models.JSONField(default=dict, verbose_name='Positie')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Geverifieerd')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing_ocr.invoiceimport', verbose_name='Import')),
            ],
            options={
                'verbose_name': 'Geïmporteerde Regel',
                'verbose_name_plural': 'Geïmporteerde Regels',
                'ordering': ['volgorde'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Patroon Naam')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('field_patterns', models.JSONField(default=dict, verbose_name='Veld Patronen')),
                ('line_patterns', models.JSONField(default=dict, verbose_name='Regel Patronen')),
                ('visual_signature', models.JSONField(default=dict, verbose_name='Visuele Signatuur')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Keer Gebruikt')),
                ('times_corrected', models.PositiveIntegerField(default=0, verbose_name='Keer Gecorrigeerd')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='Nauwkeurigheid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_patterns', to='companies.company', verbose_name='Bedrijf')),
            ],
            options={
                'verbose_name': 'Factuur Patroon',
                'verbose_name_plural': 'Factuur Patronen',
                'ordering': ['-accuracy_score', '-times_used'],
            },
        ),
        migrations.AddField(
            model_name='invoiceimport',
            name='matched_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='invoicing_ocr.invoicepattern', verbose_name='Gematchte Patroon'),
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('invoice_number', 'Factuurnummer'), ('invoice_date', 'Factuurdatum'), ('due_date', 'Vervaldatum'), ('supplier_name', 'Leverancier Naam'), ('supplier_address', 'Leverancier Adres'), ('supplier_vat', 'Leverancier BTW Nr.'), ('supplier_kvk', 'Leverancier KVK'), ('subtotal', 'Subtotaal'), ('vat_amount', 'BTW Bedrag'), ('vat_percentage', 'BTW Percentage'), ('total', 'Totaal'), ('iban', 'IBAN'), ('reference', 'Referentie'), ('description', 'Omschrijving')], max_length=30, verbose_name='Veld Type')),
                ('extraction_method', models.CharField(choices=[('regex', 'Regular Expression'), ('region', 'Vaste Regio'), ('keyword_after', 'Na Keyword'), ('keyword_below', 'Onder Keyword'), ('table_column', 'Tabel Kolom'), ('ocr_anchor', 'OCR Anker')], max_length=20, verbose_name='Extractie Methode')),
                ('config', models.JSONField(default=dict, verbose_name='Configuratie')),
                ('data_type', models.CharField(choices=[('string', 'Tekst'), ('number', 'Nummer'), ('currency', 'Bedrag'), ('date', 'Datum'), ('percentage', 'Percentage')], default='string', max_length=20, verbose_name='Data Type')),
                ('validation_rules', models.JSONField(default=dict, verbose_name='Validatie Regels')),
                ('correct_extractions', models.PositiveIntegerField(default=0)),
                ('incorrect_extractions', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioriteit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='invoicing_ocr.invoicepattern', verbose_name='Patroon')),
            ],
            options={
                'verbose_name': 'Veld Mapping',
                'verbose_name_plural': 'Veld Mappings',
                'ordering': ['pattern', 'field_type', '-priority'],
            },
        ),
    ]
