# Generated by Django 5.2.10 on 2026-01-31 15:29

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('signature_image', models.ImageField(upload_to=apps.documents.models.signature_image_path, verbose_name='Handtekening afbeelding')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standaard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opgeslagen handtekening',
                'verbose_name_plural': 'Opgeslagen handtekeningen',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('original_file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='Origineel bestand')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Originele bestandsnaam')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.signed_document_path, verbose_name='Ondertekend bestand')),
                ('signature_data', models.JSONField(blank=True, help_text='JSON met handtekening positie en metadata', null=True, verbose_name='Handtekening data')),
                ('status', models.CharField(choices=[('pending', 'Wacht op handtekening'), ('signed', 'Ondertekend'), ('expired', 'Verlopen')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ondertekend op')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Ondertekend door')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Geüpload door')),
            ],
            options={
                'verbose_name': 'Ondertekend document',
                'verbose_name_plural': 'Ondertekende documenten',
                'ordering': ['-created_at'],
            },
        ),
    ]
