# Generated by Django 5.2.12 on 2026-03-29 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Bijgewerkt op')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Chat sessie',
                'verbose_name_plural': 'Chat sessies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Gebruiker'), ('assistant', 'Assistent'), ('system', 'Systeem')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Inhoud')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Sessie')),
            ],
            options={
                'verbose_name': 'Chat bericht',
                'verbose_name_plural': 'Chat berichten',
                'ordering': ['created_at'],
            },
        ),
    ]
