# Generated by Django 5.2.10 on 2026-01-30 11:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLeaveSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_leave_hours', models.DecimalField(decimal_places=2, default=Decimal('216.00'), max_digits=6, verbose_name='Standaard verlofuren nieuwe medewerker')),
                ('standard_work_week_hours', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='Standaard werkweek uren')),
                ('overtime_leave_percentage', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage overuren opneembaar als verlof')),
                ('max_concurrent_leave', models.PositiveIntegerField(default=2, verbose_name='Max gelijktijdig verlof (waarschuwing)')),
                ('free_special_leave_hours_per_month', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Gratis bijzonder verlof uren per maand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Globale verlof instelling',
                'verbose_name_plural': 'Globale verlof instellingen',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vacation_hours', models.DecimalField(decimal_places=2, default=Decimal('216.00'), max_digits=7, verbose_name='Verlofuren')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Overuren')),
                ('special_leave_used', models.JSONField(blank=True, default=dict, verbose_name='Bijzonder verlof gebruikt per maand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL, verbose_name='Medewerker')),
            ],
            options={
                'verbose_name': 'Verlofsaldo',
                'verbose_name_plural': "Verlofsaldo's",
                'ordering': ['user__achternaam', 'user__voornaam'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('vakantie', 'Vakantie'), ('overuren', 'Verlof overuren'), ('bijzonder_tandarts', 'Bijzonder verlof tandarts'), ('bijzonder_huisarts', 'Bijzonder verlof huisarts')], max_length=30, verbose_name='Type verlof')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Einddatum')),
                ('hours_requested', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Uren aangevraagd')),
                ('reason', models.TextField(blank=True, verbose_name='Reden / opmerking')),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('approved', 'Goedgekeurd'), ('rejected', 'Afgewezen'), ('cancelled', 'Geannuleerd')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Admin opmerking')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Beoordeeld op')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangevraagd op')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Beoordeeld door')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Medewerker')),
            ],
            options={
                'verbose_name': 'Verlofaanvraag',
                'verbose_name_plural': 'Verlofaanvragen',
                'ordering': ['-created_at'],
            },
        ),
    ]
