# Generated by Django 5.2.10 on 2026-01-31 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing_ocr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_message_id', models.CharField(help_text='Uniek ID van de email', max_length=500, verbose_name='Message ID')),
                ('email_subject', models.CharField(max_length=500, verbose_name='Onderwerp')),
                ('email_from', models.CharField(max_length=255, verbose_name='Van')),
                ('email_date', models.DateTimeField(verbose_name='E-mail Datum')),
                ('email_body_preview', models.TextField(blank=True, help_text='Eerste deel van de email body', verbose_name='Voorvertoning')),
                ('status', models.CharField(choices=[('pending', 'In wachtrij'), ('processing', 'Verwerken'), ('awaiting_review', 'Wacht op Review'), ('approved', 'Goedgekeurd'), ('rejected', 'Afgewezen'), ('completed', 'Voltooid'), ('failed', 'Mislukt')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Foutmelding')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Verwerkt op')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Gereviewd op')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_email_imports', to=settings.AUTH_USER_MODEL, verbose_name='Gereviewd door')),
            ],
            options={
                'verbose_name': 'E-mail Import',
                'verbose_name_plural': 'E-mail Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='Originele Bestandsnaam')),
                ('file', models.FileField(upload_to='imports/email_attachments/', verbose_name='Bestand')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Bestandsgrootte')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Verwerkt')),
                ('error_message', models.TextField(blank=True, verbose_name='Foutmelding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_import', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_source', to='invoicing_ocr.invoiceimport', verbose_name='Factuur Import')),
                ('email_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_import.emailimport', verbose_name='E-mail Import')),
            ],
            options={
                'verbose_name': 'E-mail Bijlage',
                'verbose_name_plural': 'E-mail Bijlages',
                'ordering': ['email_import', 'original_filename'],
            },
        ),
        migrations.CreateModel(
            name='MailboxConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Configuratie Naam')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('ms365', 'Microsoft 365 (OAuth)')], default='imap', max_length=20, verbose_name='Protocol')),
                ('status', models.CharField(choices=[('active', 'Actief'), ('inactive', 'Inactief'), ('error', 'Fout')], default='inactive', max_length=20, verbose_name='Status')),
                ('imap_server', models.CharField(blank=True, help_text='bijv. outlook.office365.com', max_length=255, verbose_name='IMAP Server')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='IMAP Poort')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='SSL Gebruiken')),
                ('email_address', models.EmailField(max_length=254, verbose_name='E-mail Adres (Shared Mailbox)')),
                ('_username', models.CharField(blank=True, max_length=500, verbose_name='Gebruikersnaam (versleuteld)')),
                ('_password', models.CharField(blank=True, max_length=500, verbose_name='Wachtwoord (versleuteld)')),
                ('ms365_client_id', models.CharField(blank=True, max_length=255, verbose_name='MS365 Client ID')),
                ('_ms365_client_secret', models.CharField(blank=True, max_length=500, verbose_name='MS365 Client Secret (versleuteld)')),
                ('ms365_tenant_id', models.CharField(blank=True, max_length=255, verbose_name='MS365 Tenant ID')),
                ('folder_name', models.CharField(default='INBOX', max_length=100, verbose_name='Map om te Monitoren')),
                ('mark_as_read', models.BooleanField(default=True, verbose_name='Als Gelezen Markeren')),
                ('move_to_folder', models.CharField(blank=True, help_text='Optioneel: verplaats verwerkte mails naar deze map', max_length=100, verbose_name='Verplaats naar Map')),
                ('only_unread', models.BooleanField(default=True, verbose_name='Alleen Ongelezen')),
                ('subject_filter', models.CharField(blank=True, help_text='Optioneel: alleen mails die dit bevatten', max_length=255, verbose_name='Onderwerp Filter')),
                ('sender_filter', models.CharField(blank=True, help_text='Optioneel: alleen mails van dit adres/domein', max_length=255, verbose_name='Afzender Filter')),
                ('auto_fetch_enabled', models.BooleanField(default=False, verbose_name='Automatisch Ophalen')),
                ('auto_fetch_interval_minutes', models.PositiveIntegerField(default=15, verbose_name='Interval (minuten)')),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatst Opgehaald')),
                ('last_error', models.TextField(blank=True, verbose_name='Laatste Fout')),
                ('total_emails_processed', models.PositiveIntegerField(default=0, verbose_name='Totaal Verwerkte E-mails')),
                ('total_invoices_imported', models.PositiveIntegerField(default=0, verbose_name='Totaal Geïmporteerde Facturen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_configs', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
            ],
            options={
                'verbose_name': 'Mailbox Configuratie',
                'verbose_name_plural': 'Mailbox Configuraties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailimport',
            name='mailbox_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='email_import.mailboxconfig', verbose_name='Mailbox Configuratie'),
        ),
        migrations.AlterUniqueTogether(
            name='emailimport',
            unique_together={('mailbox_config', 'email_message_id')},
        ),
    ]
