# Generated by Django 5.2.10 on 2026-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxconfig',
            name='folder_name',
            field=models.CharField(default='INBOX', max_length=500, verbose_name='Map om te Monitoren'),
        ),
        migrations.AlterField(
            model_name='mailboxconfig',
            name='move_to_folder',
            field=models.CharField(blank=True, help_text='Optioneel: verplaats verwerkte mails naar deze map', max_length=500, verbose_name='Verplaats naar Map'),
        ),
    ]
