# Generated by Django 5.2.10 on 2026-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0002_increase_folder_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxconfig',
            name='folder_display_name',
            field=models.CharField(default='INBOX', help_text='Leesbare naam van de map', max_length=255, verbose_name='Map Naam'),
        ),
        migrations.AddField(
            model_name='mailboxconfig',
            name='move_to_folder_display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verplaats naar Map Naam'),
        ),
        migrations.AlterField(
            model_name='mailboxconfig',
            name='folder_name',
            field=models.CharField(default='INBOX', max_length=500, verbose_name='Map ID'),
        ),
        migrations.AlterField(
            model_name='mailboxconfig',
            name='move_to_folder',
            field=models.CharField(blank=True, help_text='Optioneel: verplaats verwerkte mails naar deze map', max_length=500, verbose_name='Verplaats naar Map ID'),
        ),
    ]
