# Generated by Django 5.2.10 on 2026-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_import', '0003_add_folder_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxconfig',
            name='default_invoice_type',
            field=models.CharField(choices=[('purchase', 'Inkoop'), ('credit', 'Credit'), ('sales', 'Verkoop')], default='purchase', help_text='Het type factuur dat vanuit deze mailbox geïmporteerd wordt', max_length=20, verbose_name='Standaard Factuurtype'),
        ),
    ]
