# Generated by Django 5.2.10 on 2026-01-27 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weeknummer', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('jaar', models.PositiveIntegerField(verbose_name='Jaar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='companies.company', verbose_name='Bedrijf')),
            ],
            options={
                'verbose_name': 'Weekplanning',
                'verbose_name_plural': 'Weekplanningen',
                'ordering': ['-jaar', '-weeknummer'],
                'unique_together': {('bedrijf', 'weeknummer', 'jaar')},
            },
        ),
        migrations.CreateModel(
            name='PlanningEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dag', models.CharField(choices=[('ma', 'Maandag'), ('di', 'Dinsdag'), ('wo', 'Woensdag'), ('do', 'Donderdag'), ('vr', 'Vrijdag')], max_length=2, verbose_name='Dag')),
                ('telefoon', models.CharField(blank=True, max_length=20, verbose_name='Telefoon')),
                ('adr', models.BooleanField(default=False, verbose_name='ADR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_entries', to='drivers.driver', verbose_name='Chauffeur')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_entries', to='fleet.vehicle', verbose_name='Voertuig')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planning.weekplanning', verbose_name='Planning')),
            ],
            options={
                'verbose_name': 'Planningsregel',
                'verbose_name_plural': 'Planningsregels',
                'ordering': ['dag'],
            },
        ),
    ]
