# Generated by Django 5.2.10 on 2026-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planningentry_ritnummer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningentry',
            options={'ordering': ['vehicle__ritnummer', 'dag'], 'verbose_name': 'Planningsregel', 'verbose_name_plural': 'Planningsregels'},
        ),
    ]
